openapi: 3.0.0
info:
  title: Flawed User API
  version: 1.0.0
  description: An API to create users.
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
      responses:
        '201':
          description: User created successfully