openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: API for managing users

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's full name
                email:
                  type: string
                  format: email
                  description: User's email address
                age:
                  type: integer
                  description: User's age
                  minimum: 0
                  maximum: 150
              required:
                - name
                - email
                - age
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
