openapi: 3.0.0
info:
  title: Flawed LOCAL User API
  version: 1.0.0
  description: An API to create users that is missing 'email' in its spec.
servers:
  - url: http://127.0.0.1:5000
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
      responses:
        '201':
          description: User created successfully